import { Stock, MergerTarget, MarketNews } from "../types";

export const initialStocks: Stock[] = [
  {
    ticker: "NVDA",
    name: "NVIDIA Corp.",
    currentPrice: 450.0,
    priceHistory: [410.0, 425.0, 400.0, 435.0, 450.0],
    sharesOwned: 0,
    avgBuyPrice: 0.0,
    volatility: 0.28,
    sector: "Tech",
    dailyTrendFactor: 1.0,
  },
  {
    ticker: "AAPL",
    name: "Apple Inc.",
    currentPrice: 185.0,
    priceHistory: [182.0, 180.0, 186.0, 183.0, 185.0],
    sharesOwned: 0,
    avgBuyPrice: 0.0,
    volatility: 0.12,
    sector: "Tech",
    dailyTrendFactor: 1.0,
  },
  {
    ticker: "TSLA",
    name: "Tesla Inc.",
    currentPrice: 210.0,
    priceHistory: [235.0, 220.0, 195.0, 205.0, 210.0],
    sharesOwned: 0,
    avgBuyPrice: 0.0,
    volatility: 0.35,
    sector: "Energy",
    dailyTrendFactor: 1.0,
  },
  {
    ticker: "SLRS",
    name: "Solaris GreenTech",
    currentPrice: 25.0,
    priceHistory: [22.0, 26.0, 21.0, 23.0, 25.0],
    sharesOwned: 0,
    avgBuyPrice: 0.0,
    volatility: 0.45,
    sector: "Energy",
    dailyTrendFactor: 1.0,
  },
  {
    ticker: "BYGN",
    name: "BioGen Labs",
    currentPrice: 85.0,
    priceHistory: [92.0, 89.0, 81.0, 86.0, 85.0],
    sharesOwned: 0,
    avgBuyPrice: 0.0,
    volatility: 0.22,
    sector: "Biotech",
    dailyTrendFactor: 1.0,
  },
  {
    ticker: "GME",
    name: "GameStop Retail",
    currentPrice: 18.0,
    priceHistory: [12.0, 32.0, 9.0, 14.0, 18.0],
    sharesOwned: 0,
    avgBuyPrice: 0.0,
    volatility: 0.85,
    sector: "Meme",
    dailyTrendFactor: 1.0,
  }
];

export const initialMergers: MergerTarget[] = [
  {
    id: "solaris",
    name: "Project Zephyr: Solaris",
    sector: "Energy",
    ceoName: "Elena Vance",
    ceoAvatar: "👩‍💼",
    description: "Solaris GreenTech owns premium ultra-dense lithium chemical patents which could monopolize the future green grid. Their technical team is robust, but they lack the heavy liquidity to build multi-state extraction refineries.",
    baseValuation: 512.4,
    minAcceptableThreshold: 460.0,
    currentAskingPrice: 512.4,
    trust: 50,
    mood: "Reasonable",
    synergyText: "Boosts green tech prestige. Restores 15% stock growth to energy holdings. Generates passive income of +$1.8M/day.",
    dailyIncome: 1.8,
    techStockBoost: 1.15,
    dialogueQuote: "“We won't accept anything less than 22% equity share and a board seat. If your numbers don't reflect our Q4 growth forecasts, there is simply no deal.”",
    termBoardSeat: false,
    termEquityShare: false,
    termRetainCEO: false,
    arguedValuationCount: 0,
    highlightedSynergiesCount: 0,
    isCompleted: false,
    isWalkedOut: false
  },
  {
    id: "nova",
    name: "Nova Robotics Corp",
    sector: "Tech",
    ceoName: "Victor Sterling",
    ceoAvatar: "👨‍💻",
    description: "Nova is developing artificial intelligence systems for automated robotic machinery. They are on the verge of public IPO but prefer private funding if the valuation reflects their hyper-scalable proprietary AI model.",
    baseValuation: 850.0,
    minAcceptableThreshold: 780.0,
    currentAskingPrice: 850.0,
    trust: 45,
    mood: "Defensive",
    synergyText: "Powers high-frequency tech stock trends (+30%). Grants exceptional computer industrial passive cash flow of +$3.5M/day.",
    dailyIncome: 3.5,
    techStockBoost: 1.30,
    dialogueQuote: "“Apex Capital thinks they can buy us out cheap? Nova Robotics is the absolute future. Meet our terms, or we walk and go public IPO ourselves next quarter.”",
    termBoardSeat: false,
    termEquityShare: false,
    termRetainCEO: false,
    arguedValuationCount: 0,
    highlightedSynergiesCount: 0,
    isCompleted: false,
    isWalkedOut: false
  },
  {
    id: "biogen",
    name: "BioGen Therapeutics",
    sector: "Biotech",
    ceoName: "Dr. Clara Wu",
    ceoAvatar: "👩‍🔬",
    description: "Dr. Wu's laboratory has formulated a target-driven cancer vaccine. However, clinical testing budgets have depleted their accounts. They need an ethical institutional backer that values patient science over quick margins.",
    baseValuation: 280.0,
    minAcceptableThreshold: 220.0,
    currentAskingPrice: 280.0,
    trust: 60,
    mood: "Reasonable",
    synergyText: "Grants outstanding health market and stable research prestige. Yields passive licensing royalty revenue of +$1.1M/day.",
    dailyIncome: 1.1,
    techStockBoost: 1.10,
    dialogueQuote: "“Our initial trial arrays show 92% efficacy rates. We are seeking a dedicated long-term investment partner who values scientific integrity, not standard liquid spreadsheets.”",
    termBoardSeat: false,
    termEquityShare: false,
    termRetainCEO: false,
    arguedValuationCount: 0,
    highlightedSynergiesCount: 0,
    isCompleted: false,
    isWalkedOut: false
  },
  {
    id: "zenith",
    name: "Zenith Power Utility",
    sector: "Energy",
    ceoName: "Marcus 'Bull' Hudson",
    ceoAvatar: "👨‍💼",
    description: "An old-school energy megacorporation owning hundreds of fossil generator grids. Marcus is extremely proud, skeptical of tech, and wants massive cash reserves to secure his inheritance before retirement.",
    baseValuation: 1200.0,
    minAcceptableThreshold: 1100.0,
    currentAskingPrice: 1200.0,
    trust: 30,
    mood: "Greedy",
    synergyText: "Instantly establishes energy empire hegemony. Grants immense passive electrical grid dividends of +$5.5M/day.",
    dailyIncome: 5.5,
    techStockBoost: 1.05,
    dialogueQuote: "“My corporate advisors tell me Apex Capital has deep finance lines. Well, talk is cheap. Show me real cash liquidity, or don't try to sit at my board table.”",
    termBoardSeat: false,
    termEquityShare: false,
    termRetainCEO: false,
    arguedValuationCount: 0,
    highlightedSynergiesCount: 0,
    isCompleted: false,
    isWalkedOut: false
  }
];

export const newsList: MarketNews[] = [
  {
    headline: "Apex Capital Appoints New Director",
    description: "You have assumed absolute control as Managing Partner at Apex Capital. The board has allocated $150.0M liquid cash to scale our investment portfolios or orchestrate key strategic corporate buyouts.",
    affectedTicker: "ALL",
    priceMultiplier: 1.0,
    isPositive: true,
  },
  {
    headline: "NVIDIA Quantum Superchip Shatters Speed Benchmarks!",
    description: "Global tech journals are calling NVIDIA's new hardware architecture the pinnacle of computing logic, initiating a tidal wave of retail and institutional buyers.",
    affectedTicker: "NVDA",
    priceMultiplier: 1.22,
    isPositive: true,
  },
  {
    headline: "Solaris GreenTech Secures Massive Lithium Squeeze!",
    description: "Elena Vance has outmaneuvered international mining cartels, securing an exclusive lithium refining monopoly. Energy sectors are highly reactive.",
    affectedTicker: "SLRS",
    priceMultiplier: 1.28,
    isPositive: true,
  },
  {
    headline: "BioGen Laboratory Cancer Antigen Trials Break records!",
    description: "Regulatory review boards have greenlighted Phase 3 breakthrough expedite programs. Scientists claim clinical results surpass all standard therapies.",
    affectedTicker: "BYGN",
    priceMultiplier: 1.35,
    isPositive: true,
  },
  {
    headline: "Superstonk Forums Ignite Massive Short Squeeze on GameStop!",
    description: "Retail brokerages report historic volume as short positions are forcefully liquidated. Expect maximum trading high-risk volatility today.",
    affectedTicker: "GME",
    priceMultiplier: 2.10,
    isPositive: true,
  },
  {
    headline: "Federal Reserve Slashes Interest Rates Unexpectedly!",
    description: "The monetary policy adjustment eases capital availability across all corporate boards. High-beta stocks prepare to rocket.",
    affectedTicker: "ALL",
    priceMultiplier: 1.08,
    isPositive: true,
  },
  {
    headline: "Securities Council Launches Probe into Silicon Valley Exports",
    description: "Officials cite possible compliance omissions. Advanced technology stocks decline steadily as panic spreads in automated trade desks.",
    affectedTicker: "AAPL",
    priceMultiplier: 0.88,
    isPositive: false,
  },
  {
    headline: "NVIDIA Server Farm Overheats, Shipping Delay Projected",
    description: "Analysts fear a minor Q3 revenue guidance shortfall. Competitors look to seize the market cap vacuum.",
    affectedTicker: "NVDA",
    priceMultiplier: 0.90,
    isPositive: false,
  },
  {
    headline: "Tesla AI Autonomous Guidance Stumbles on Trial",
    description: "A software glitch in commuter beta builds triggers regulatory scrutiny and safety investigations. High short volume recorded.",
    affectedTicker: "TSLA",
    priceMultiplier: 0.82,
    isPositive: false,
  },
  {
    headline: "BioGen Suffers High Bio-synthetic Manufacturing Waste",
    description: "Meticulous purification runs failed quality benchmarks, causing a temporary logistical delay. Stock registers substantial drop.",
    affectedTicker: "BYGN",
    priceMultiplier: 0.78,
    isPositive: false,
  },
  {
    headline: "Epic Blizzard Destroys Solaris GreenTech Solar Array Farm",
    description: "Sub-zero temperatures and panel damage degrade grid output capability, prompting conservative Q4 cash estimations.",
    affectedTicker: "SLRS",
    priceMultiplier: 0.80,
    isPositive: false,
  },
  {
    headline: "Apple Unleashes Revolutionary 'Vision glass' Holographics",
    description: "Preorders shatter previous records inside high-income demographics. Analysts rate the stock a unanimous strong buy.",
    affectedTicker: "AAPL",
    priceMultiplier: 1.15,
    isPositive: true,
  },
  {
    headline: "Short Sellers Target GameStop After Secondary Offering",
    description: "The corporate board leverages the high market prices to issue millions of new shares, diluting retail dominance.",
    affectedTicker: "GME",
    priceMultiplier: 0.60,
    isPositive: false,
  },
  {
    headline: "Global Energy Coalition Standardizes Green Credits",
    description: "Grid companies complying with renewable outputs receive direct taxation exemptions, heavily supporting solar companies.",
    affectedTicker: "SLRS",
    priceMultiplier: 1.12,
    isPositive: true,
  },
  {
    headline: "Tesla Unveils Battery Megapack with 35% Higher Density",
    description: "CEO promises rapid deployment across desert utility nodes, solidifying industrial energy dominance.",
    affectedTicker: "TSLA",
    priceMultiplier: 1.16,
    isPositive: true,
  }
];
